### ISSUE TITLE
Font value

### ISSUE THREAD

**Issue by hend0298** [hend0298/responsive-header#1]
@thomasjbradley Markbot says there's supposed to be a different font value in the css for html and I can't figure out what it wants me to put.

**Comment by thomasjbradley** [comment]
You can always look inside the `.markbot.yml` file to see exactly what it expects, this is what Markbot wants for this assignment:

```css
html {
  font: normal 100%/1.3 Ubuntu, sans-serif;
}
```
